syntax = "proto3";

package user.v1;

option go_package = "rahulxf.com/rpc-learning/internal/gen/go/user/v1;userv1";

message User {
    string id = 1;
    string email = 2;
    string name = 3;
    string phone = 4;
    int64 created_at = 5;
    UserStatus status = 6;
    Address address = 7;
}

message Address {
    string street = 1;
    string city   = 2;
}

enum UserStatus {
    USER_STATUS_UNSPECIFIED = 0;
    USER_STATUS_ACTIVE = 1;
    USER_STATUS_INACTIVE = 2;
}

enum MaritalStatus {
    MARITAL_STATUS_UNSPECIFIED = 0;
    MARITAL_STATUS_SINGLE      = 1;
    MARITAL_STATUS_MARRIED     = 2;
}

// services

service UserService {
    rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
    rpc GetUser(GetUserRequest) returns (GetUserResponse);
    rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse);
    rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
    rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
}

message CreateUserRequest {
    string email =1;
    string name = 2;
    optional string phone = 3;
}

message CreateUserResponse {
    User user = 1;
    string message = 2;
}

message GetUserRequest {
    string id = 1;
}

message GetUserResponse {
    User user = 1;
}

message UpdateUserRequest {
    string id = 1;
    optional string name = 2;
    optional string phone = 3;
}

message UpdateUserResponse {
    User user = 1;
}

message DeleteUserRequest {
    string id = 1;
}

message DeleteUserResponse {
    bool success = 1;
}

message ListUsersRequest {
    int32 page_size = 1;
    string page_token = 2;
}

message ListUsersResponse {
    repeated User users = 1;
    string next_page_token = 2;
}



